version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: Australia/Brisbane
      time: '06:00'
    reviewers:
      - andrewmcLachlan
    groups:
      dev-dependences:
        applies-to: version-updates
        patterns:
          - "*"
        dependency-type: "development"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "weekly"
      timezone: Australia/Brisbane
      day: monday
      time: '06:00'
    reviewers:
      - andrewmcLachlan

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: Australia/Brisbane
      day: monday
      time: '06:00'
    reviewers:
      - andrewmcLachlan
