version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Australia/Brisbane
      day: "monday"
      time: '06:00'
    reviewers:
      - AndrewMcLachlan
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        dependency-type: "development"
      prod-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        dependency-type: "production"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directory: "/moo-app"
    schedule:
      interval: "weekly"
      timezone: Australia/Brisbane
      day: monday
      time: '06:00'
    reviewers:
      - AndrewMcLachlan
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        dependency-type: "development"
      prod-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/moo-icons"
    schedule:
      interval: "weekly"
      timezone: Australia/Brisbane
      day: monday
      time: '06:00'
    reviewers:
      - AndrewMcLachlan
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        dependency-type: "development"
      prod-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/demoo"
    schedule:
      interval: "weekly"
      timezone: Australia/Brisbane
      day: monday
      time: '06:00'
    reviewers:
      - AndrewMcLachlan
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        dependency-type: "development"
      prod-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        dependency-type: "production"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: Australia/Brisbane
      day: monday
      time: '06:00'
    reviewers:
      - AndrewMcLachlan
