version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Australia/Brisbane
      day: monday
      time: '06:00'
    reviewers:
      - andrewmcLachlan

  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "weekly"
      timezone: Australia/Brisbane
      day: monday
      time: '06:00'
    reviewers:
      - andrewmcLachlan

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: Australia/Brisbane
      day: monday
      time: '06:00'
    reviewers:
      - andrewmcLachlan
