import React, { createContext, useCallback, useMemo, useState } from "react";
import { useContext } from "react";
import { type Message, type Messages } from "../models";

let nextKey = 0;

export const MessageContext = createContext<Messages | undefined>(undefined);

export const MessageProvider: React.FC<React.PropsWithChildren> = ({ children }) => {

    const [messages, setMessages] = useState<Message[]>([]);

    const sendMessage = useCallback((message: Message) => {
        message.key ??= `autogenerated-message${nextKey++}`;
        setMessages(prev => [...prev.filter(m => m.key !== message.key), message]);
    }, []);

    const clearMessage = useCallback((key: string) => {
        setMessages(prev => prev.filter(m => m.key !== key));
    }, []);

    const value = useMemo<Messages>(() => ({ messages, sendMessage, clearMessage }), [messages, sendMessage, clearMessage]);

    return (
        <MessageContext.Provider value={value}>
            {children}
        </MessageContext.Provider>
    );
}

export const useMessages = () => {
    const context = useContext(MessageContext);
    if (!context) {
        throw new Error("useMessages must be used within a MessageProvider");
    }
    return context;
};
